### ISSUE TITLE
motivation?

### ISSUE THREAD

**Issue by BurntSushi** [magiclen/escape-regex#1]
Would you mind adding a blurb to the README describing the motivation for this crate? In particular, what is the purpose of this crate when the [`regex` crate itself provides an `escape` function](https://docs.rs/regex/1.1.0/regex/fn.escape.html)? Moreover, your implementation of `escape` is incorrect. It's missing 4 special characters. (`#`, `~`, `-` and `&`.)

Also, I found it difficult to find this repository. Please add a repository link to your `Cargo.toml`. The [current homepage](https://github.com/magiclen/escape-regex/blob/fc6e0273f86bcdadc93393551ab23e472382758b/Cargo.toml#L5) link seems to have nothing to do with this project.

**Comment by magiclen** [comment]
Oops, I didn't notice that there is an `escape` function in the `regex` crate. And I also forgot to add the repository link of this repository. Thank you for reminding me. I'm so sorry about wasting your time.

[This crate on crates.io](https://crates.io/crates/escape-regex) has been yanked.
